config/routes.rb
Nilgiri::Application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :players, controllers: {
    sessions: 'players/sessions',
    registrations: 'players/registrations',
    passwords: 'players/passwords'
  }
  root to: 'home#index'
  resources :scores, only: [:index, :new, :create, :destroy]
  resources :musics, only: [:index, :show]
  resources :machines, only: [:index, :show] do
    resources :musics, only: [:index, :show]
  end
  resources :seasons, only: [:index, :show]
  resources :posts
  resources :players, only: [:index, :show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(updated_at: :desc)
    n = @posts.count
    @top_post = @posts.first
    if n >= 2
      @recent_posts = @posts.offset(1).limit(5)
      @is_more_posts = n > 6
    end

    if @current_season.present?
      @top_scores = Hash[Machine.all.map {|machine|
        [machine, machine.get_top_scores(@current_season)]
      }]
    end
  end
end

app/views/home/_rank.haml
%thead
  %tr
    %th Difficulty
    %th 1st
    %th 2nd
    %th 3rd
%tbody
  - item.each do |difficulty, scores|
    %tr
      %td= difficulty
      - for score in scores
        %td
          %span.name= score.player.name
          %br
          %span.score= score.score

app/views/home/index.html.haml
.top-banner.text-center
  %h1
    Nilgiri
    %small TEA party score registration tool
  - if player_signed_in?
    = link_to 'Submit Score', new_score_path, class: "large button success radius"
  - else
    = link_to 'Sign up', new_player_registration_path, class: "large button success radius"
    %br
    Already have an account?
    = link_to 'Sign in', new_player_session_path

.row
  %h1= link_to 'News', posts_path
  - if @top_post
    .show-for-medium-up
      %section#top-post.panel.small-6.columns
        %h2
          = link_to @top_post.title, post_path(@top_post)
          %small= @top_post.updated_at.strftime('%Y-%m-%d')
        %p.show-for-medium-up= truncate(@top_post.body, length: 100)
        %p.show-for-small-only= truncate(@top_post.body, length: 30)
      - if @recent_posts.present?
        %section.small-6.columns
          %h2 More Articles
          %ul.small-block-grid-5
            - for post in @recent_posts
              %li
                .show-for-medium-up
                  = link_to post.title, post_path(post)
                  %br
                  %small= post.updated_at.strftime('%Y-%m-%d')
                .show-for-small-only
                  = link_to truncate(post.title, length: 20), post_path(post)
          - if @is_more_posts
            %p= link_to 'more...', posts_path
    .show-for-small-only
      %ul
        %li
          %b= link_to @top_post.title, @top_post
        - @recent_posts.each do |post|
          %li= link_to post.title, post
  - else
    %p No news articles.

- if @current_season.present?
  .row
    .small-12.columns
      %p
        We are now in the season
        = surround '"' do
          %strong= @current_season.name
        (till #{@current_season.expiry})

- if @top_scores.present?
  .row
    .small-12.columns
      %h1
        Top
        %small for #{@current_season.name}
      .row
        %dl.vertical.tabs{data: {tab: true}, style: 'word-wrap: break-word;'}
          - for machine in Machine.all
            %dd= link_to machine.name, "##{machine.slug}"
        .small-12.columns.vertical.tabs-content
          - @top_scores.each do |machine, musics|
            .content{id: machine.slug, style: 'width: 100%;'}
              .row
                %h2= link_to machine.name, machine_path(machine)
                - musics.each do |music, item|
                  %h3= music.name
                  - if machine.playstyles.present?
                    .row
                      - item.each do |playstyle, item|
                        .large-6.small-12.columns
                          %table
                            %caption= playstyle
                            = render partial: 'rank', locals: { item: item }
                  - else
                    %table
                      = render partial: 'rank', locals: { item: item }