config/routes.rb
Nilgiri::Application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :players, controllers: {
    sessions: 'players/sessions',
    registrations: 'players/registrations',
    passwords: 'players/passwords'
  }
  root to: 'home#index'
  resources :scores, only: [:index, :new, :create, :destroy]
  resources :musics, only: [:index, :show]
  resources :machines, only: [:index, :show] do
    resources :musics, only: [:index, :show]
  end
  resources :seasons, only: [:index, :show]
  resources :posts
  resources :players, only: [:index, :show]
end

app/models/player.rb
require 'scrypt'

class Player < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :encryptable
  has_many :scores

  validates :name, presence: true

  def register_score(season: nil, music: nil, difficulty: nil, score: nil, playstyle: nil)
    [season, music, difficulty, score].each do |v|
      raise ArgumentError unless v
    end
    q = scores.where(season: season, music: music, difficulty: difficulty)
    q = q.where(playstyle: playstyle) if playstyle
    s = q.first
    if s
      s.score = score if s.score < score
    else
      s = self.scores.build(
        season: season,
        music: music,
        difficulty: difficulty,
        playstyle: playstyle,
        score: score
      )
    end
    s
  end
end

app/controllers/players/passwords_controller.rb
class Players::PasswordsController < Devise::PasswordsController
end

app/controllers/players/registrations_controller.rb
class Players::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name << :twitter_id
    devise_parameter_sanitizer.for(:account_update) << :name << :twitter_id
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_update_path_for(resource)
    player_path(resource)
  end
end

app/controllers/players/sessions_controller.rb
class Players::SessionsController < Devise::SessionsController
  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end
end

app/views/players/show.html.haml
.row
  .small-12.columns
    %h1
      = @player.name
      - if @player.twitter_id.present?
        %small= link_to "@#{@player.twitter_id}", "https://twitter.com/#{@player.twitter_id}"
    - if @player == current_player
      = link_to 'Edit Profile', edit_player_registration_path(@player)

.row
  .small-12.columns
    %h2 Scores
    %table
      %thead
        %tr
          %th Season
          %th Machine
          %th Music
          %th Difficulty
          %th Play style
          %th Score
          %th Updated at
          - if @player == current_player
            %th
      %tbody
        - @player.scores.order(updated_at: :desc).each do |score|
          %tr
            %td= link_to score.season.name, season_path(score.season)
            %td= link_to score.music.machine.name, machine_path(score.music.machine)
            %td= link_to score.music.name, music_path(score.music)
            %td= score.difficulty
            %td= score.playstyle.presence || 'N/A'
            %td= score.score
            %td= score.updated_at
            - if @player == current_player
              %td= link_to 'Destroy', score, :method => :delete, :data => { :confirm => 'Are you sure?' }

.row
  .small-12.columns
    = link_to 'Back', players_path