config/routes.rb
Nilgiri::Application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :players, controllers: {
    sessions: 'players/sessions',
    registrations: 'players/registrations',
    passwords: 'players/passwords'
  }
  root to: 'home#index'
  resources :scores, only: [:index, :new, :create, :destroy]
  resources :musics, only: [:index, :show]
  resources :machines, only: [:index, :show] do
    resources :musics, only: [:index, :show]
  end
  resources :seasons, only: [:index, :show]
  resources :posts
  resources :players, only: [:index, :show]
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %title
      - if @title.present?
        #{@title} | Nilgiri
      - else
        Nilgiri
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "vendor/modernizr", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header.contain-to-grid
      %nav.top-bar{data: {topbar: true}}
        %ul.title-area
          %li.name
            %h1
              %a{href: '/'} Nilgiri
        %section.top-bar-section
          %ul.right
            %li
              - if @current_season.present?
                %a{href: '#'} Season: #{@current_season.name}
            - if user_signed_in?
              %li= link_to 'Admin', rails_admin_path, class: 'tiny alert radius button'
            - if player_signed_in?
              %li
                = link_to current_player.name, player_path(current_player)
              %li= link_to 'Sign out', destroy_player_session_path, method: :delete
            - else
              %li= link_to 'Sign in', new_player_session_path
              %li= link_to 'Sign up', new_player_registration_path, class: 'tiny secondary radius button'
          %ul.left
            %li= link_to 'Submit Score', new_score_path
            %li= link_to 'Recent Scores', scores_path
            %li= link_to 'Players', players_path
            %li.has-dropdown
              = link_to 'Machines', machines_path
              %ul.dropdown
                - for machine in Machine.all
                  %li= link_to machine.name, machine_path(machine)
    #main-content{data: { page_id: @page_id.presence }}
      .row
        - for kind in %i(alert success warning info)
          - if flash[kind].present?
            %div{class: "flash alert-box #{kind} radius text-center", data: {alert: true}}
              != flash[kind]
              %a.close{href: '#'} &times;
      != yield
    %footer
      .text-right
        %small
          author:
          = link_to 'Mei Akizuru', 'https://twitter.com/maytheplic'
          %br
          github:
          = link_to 'mayth/nilgiri', 'https://github.com/mayth/nilgiri'
    = javascript_include_tag "application"